language: go

sudo: false

go:
  - 1.4

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go get ./...
  - go test ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - tools/collate_validate/check.sh
  - tools/validate/check.sh
